@echo off
cd /d "%~dp0"
echo Checking Python version...
python --version
echo Checking pip version...
python -m pip --version
echo Updating pip...
python -m pip install -U pip
echo.
echo Installing requirements please wait patiently...
python -m pip install -U -r requirements.txt
python -m pip install -U -r pytorch_fix.txt
pause